version: "3.9"
services:
  frontend:
    image : httpd:latest
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes :
      - ~/tmp/multiple-dockercompose-example/frontend-service/public-html:/usr/local/apache2/htdocs
