version: "3.9"
services:
  frontend:
    build: .
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes :
      - ${REPO_DIRECTORY}/multiple-dockercompose-example/frontend-service/public-html:/usr/local/apache2/htdocs
